services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: db-capibara
    environment:
      POSTGRES_DB: capibara
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d capibara"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes: # add this section
  postgres_data:
